/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import ifsc.poo.geom.*;
import ifsc.poo.joe.*;

public class App {
    public static void javaOfEmpires() {
        Aldeao aldeao = new Aldeao();
        Arqueiro arqueiro = new Arqueiro();
        Cavaleiro cavaleiro = new Cavaleiro();

        System.out.println(aldeao.mover());
        System.out.println(arqueiro.mover());
        System.out.println(cavaleiro.mover());

        System.out.println(aldeao.atacar());
        System.out.println(arqueiro.atacar());
        System.out.println(cavaleiro.atacar());
    }

    public static void geometria2D() {
        Linha l1 = new Linha(0, 0, 1, 1);
        Ponto l1_ini = l1.getIni();

    }

    public static void main(String[] args) {
        javaOfEmpires();
    }
}
